---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    api_info: &api_info
      api_private_key: /intersight_api_private_key
      api_key_id: "{{ intersight_api_key_id }}"
    server_profile: ansible-test-server-profile
  tasks:
  - name: Configure Server Profile
    intersight_rest_api:
      <<: *api_info
      resource_path: /server/Profiles
      query_params:
        $filter: "Name eq '{{ server_profile }}'"
      api_body: {
          "Name": "{{ server_profile }}"
      }
      state: present
  # - name: Configure Server Profile
  #   intersight_objects:
  #     api_private_key: /intersight_api_private_key
  #     api_key_id: /intersight_api_key_id
  #     objects:
  #     - {
  #       "api_module": "intersight.apis.server_profile_api",
  #       "api_class": "ServerProfileApi",
  #       "api_method_prefix": "server_profiles",
  #       "get_filter": "Name eq 'ansible-demo'",
  #       "data_module": "intersight.models.server_profile",
  #       "data_class": "ServerProfile",
  #       "api_body": {
  #           "Name": "ansible-demo"
  #       }
  #     }
  #     state: present
